# Generated by Django 3.0.8 on 2020-08-01 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v_server', '0002_auto_20200717_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
