# Generated by Django 3.0.8 on 2020-08-03 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v_server', '0005_organizationusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationusers',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='v_server.Organization'),
        ),
    ]
