# Generated by Django 3.0.8 on 2020-08-04 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v_server', '0007_auto_20200803_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationusers',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='v_server.Organization'),
        ),
        migrations.AlterField(
            model_name='organizationusers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL),
        ),
    ]
