# Generated by Django 3.0.8 on 2020-08-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_server', '0009_auto_20200804_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('host', models.CharField(max_length=50)),
                ('endpoint', models.CharField(max_length=50)),
            ],
        ),
    ]
