# Generated by Django 3.0.8 on 2020-08-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_server', '0010_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='endpoints',
            field=models.ManyToManyField(blank=True, related_name='endpointList', to='v_server.Endpoint'),
        ),
    ]
