# Generated by Django 3.0.8 on 2020-10-15 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('v_server', '0011_organization_endpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=30)),
                ('longitutde', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='endpoint',
            name='parameters',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='endpoint',
            field=models.CharField(max_length=1000),
        ),
    ]
