# Generated by Django 3.0.8 on 2020-10-16 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v_server', '0012_auto_20201015_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='longitutde',
            new_name='longitude',
        ),
    ]
