# Generated by Django 3.0.8 on 2020-10-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_server', '0013_auto_20201016_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='status',
            field=models.CharField(default='successful', max_length=30),
            preserve_default=False,
        ),
    ]
